// lib/getProducts.ts
import { Product } from "../types/product";


/**
 * Returns all products
 */
export async function getProducts(): Promise<Product[]> {
  return [
    {
      id: "prod_1",
      name: "Valentino Garavani",
      image: "/vg.WEBP",
      price: 299.99,
      stripePriceId: "price_1SvMZnHBbfTMhhtur6RKt4DT",
      category: "Outfits",
      description: "Classic Valentino Garavani outfit for elegant occasions.",
      rating: 4.8,
      stock: 12,
      featured: true,
    },
    {
      id: "prod_2",
      name: "JBL Speaker",
      image: "/jbl.jpg",
      price: 2999.99,
      stripePriceId: "price_1SvPAFHBbfTMhhtu6v8H9WgG",
      category: "Electronics",
      description: "Portable JBL speaker with powerful bass and Bluetooth connectivity.",
      rating: 4.6,
      stock: 8,
      featured: true,
    },
    {
      id: "prod_3",
      name: "JBL G7x",
      image: "/jblg.jpg",
      price: 3999.99,
      stripePriceId: "",
      category: "Electronics",
      description: "High-end JBL noise-cancelling wireless headphones.",
      rating: 4.7,
      stock: 5,
      featured: false,
    },
    {
      id: "prod_4",
      name: "Hoodie",
      image: "/hoodie.jpg",
      price: 200.99,
      stripePriceId: "",
      category: "Outfits",
      description: "Comfortable cotton hoodie, perfect for casual wear.",
      rating: 4.4,
      stock: 15,
      featured: false,
    },
    {
      id: "prod_5",
      name: "T-Shirt",
      image: "/T- Shirt.JPG",
      price: 150.99,
      stripePriceId: "",
      category: "Outfits",
      description: "Soft, breathable t-shirt for everyday use.",
      rating: 4.3,
      stock: 20,
      featured: false,
    },
    {
      id: "prod_6",
      name: "CAP",
      image: "/cap.JPG",
      price: 100.99,
      stripePriceId: "",
      category: "Hats",
      description: "Stylish cap suitable for all seasons.",
      rating: 4.2,
      stock: 10,
      featured: false,
    },
    {
      id: "prod_7",
      name: "T-shirt",
      image: "/T-shirt.JPG",
      price: 150.99,
      stripePriceId: "",
      category: "Outfits",
      description: "Classic t-shirt with a modern fit.",
      rating: 4.3,
      stock: 18,
      featured: false,
    },
    {
      id: "prod_8",
      name: "Leather Snapback",
      image: "/leather Cap.WEBP",
      price: 300.99,
      stripePriceId: "",
      category: "Hats",
      description: "Premium leather snapback hat for style and comfort.",
      rating: 4.5,
      stock: 6,
      featured: true,
    },
    {
      id: "prod_9",
      name: "Bose Noise Cancelling Wireless Bluetooth Headphones",
      image: "/Bose Noise Cancelling Wireless Bluetooth.WEBP",
      price: 100.99,
      stripePriceId: "",
      category: "Electronics",
      description: "Top-quality Bose headphones for immersive sound.",
      rating: 4.8,
      stock: 7,
      featured: true,
    },
    {
      id: "prod_10",
      name: "Soundcore Q20i Wireless",
      image: "/Soundcore.WEBP",
      price: 250.99,
      stripePriceId: "",
      category: "Electronics",
      description: "Wireless Soundcore Q20i with long battery life.",
      rating: 4.4,
      stock: 9,
      featured: false,
    },
    {
      id: "prod_11",
      name: "Air Jordan 1 Retro Mid “Laser Orange Deep Royal”",
      image: "/Air JordaN.WEBP",
      price: 499.99,
      stripePriceId: "",
      category: "Sneakers",
      description: "Iconic Air Jordan sneakers for collectors and enthusiasts.",
      rating: 4.9,
      stock: 5,
      featured: false,
    },
    {
      id: "prod_12",
      name: "Adidas Samba OG",
      image: "/Samba.AVIF",
      price: 699.99,
      stripePriceId: "",
      category: "Sneakers",
      description: "Classic Adidas Samba OG for casual and sportswear.",
      rating: 4.7,
      stock: 3,
      featured: false,
    },
    {
      id: "prod_13",
      name: "NEW BALANCE 740 Men Runners Flannels",
      image: "/NewBalance.AVIF",
      price: 399.99,
      stripePriceId: "",
      category: "Sneakers",
      description: "Durable New Balance 740 for runners and daily wear.",
      rating: 4.6,
      stock: 4,
      featured: false,
    },
    {
      id: "prod_14",
      name: "GreenStride Motion 6 Waterproof Hiking Boot",
      image: "/GreenStride.WEBP",
      price: 399.99,
      stripePriceId: "",
      category: "Sneakers",
      description: "Waterproof hiking boots for outdoor adventures.",
      rating: 4.7,
      stock: 6,
      featured: true,
    },
    {
      id: "prod_15",
      name: "Avery",
      image: "/Avery.webp",
      price: 150.99,
      stripePriceId: "",
      category: "Hats",
      description: "Stylish hat for everyday fashion.",
      rating: 4.3,
      stock: 8,
      featured: false,
    },
    {
      id: "prod_16",
      name: "Carkella Del Mar Trilby-Mixed Navy",
      image: "/DelMar_MixedNavy_SM.webp",
      price: 150.99,
      stripePriceId: "",
      category: "Hats",
      description: "Elegant trilby hat with navy accents.",
      rating: 4.4,
      stock: 7,
      featured: false,
    },
    {
      id: "prod_17",
      name: "Herringbone Flat Cap",
      image: "/flat.webp",
      price: 150.99,
      stripePriceId: "",
      category: "Hats",
      description: "Classic flat cap with herringbone pattern.",
      rating: 4.3,
      stock: 6,
      featured: false,
    },
    {
      id: "prod_18",
      name: "Bluetooth Wireless Earbuds",
      image: "/bluetooth.webp",
      price: 250.99,
      stripePriceId: "",
      category: "Electronics",
      description: "High-quality Bluetooth earbuds with long battery life.",
      rating: 4.5,
      stock: 10,
      featured: false,
    },
    {
      id: "prod_19",
      name: "Silicone Cover For PS5 Controller Case Skin",
      image: "/PS5.webp",
      price: 150.99,
      stripePriceId: "",
      category: "Electronics",
      description: "Durable silicone cover to protect your PS5 controller.",
      rating: 4.2,
      stock: 25,
      featured: false,
    },
    {
      id: "prod_20",
      name: "New JBL Flip 5 Portable Waterproof",
      image: "/FLIP5.webp",
      price: 2000.99,
      stripePriceId: "",
      category: "Electronics",
      description: "Compact, waterproof JBL Flip 5 speaker for on-the-go use.",
      rating: 4.6,
      stock: 12,
      featured: true,
    },
    {
      id: "prod_21",
      name: "JBL Clip 5 Speaker Portable Waterproof",
      image: "/JBLCLIP.WEBP",
      price: 1500.99,
      stripePriceId: "",
      category: "Electronics",
      description: "Portable waterproof speaker, perfect for travel.",
      rating: 4.5,
      stock: 9,
      featured: false,
    },
    {
      id: "prod_22",
      name: "BY BENYAR Men’s Luxury Business Watch",
      image: "/BY BENYAR Mens Watches Analog Quartz.jpg",
      price: 500.99,
      stripePriceId: "",
      category: "Watches",
      description: "Chronograph Waterproof Wrist Watches for Men",
      rating: 4.5,
      stock: 9,
      featured: false,
    },
    {
      id: "prod_23",
      name: "Men's Casual Stainless Steel Watch",
      image: "/watch.jpg",
      price: 499.99,
      stripePriceId: "",
      category: "Watches",
      description: "Waterproof Luminous Chronograph Men's Watch",
      rating: 4.1,
      stock: 9,
      featured: false,
    },
    {
      id: "prod_24",
      name: "OLEVS Watch for Men Business Diamond Waterproof Wristwatch",
      image: "/OLEVS.jpg",
      price: 599.99,
      stripePriceId: "",
      category: "Watches",
      description: "Waterproof Luminous Chronograph Men's Watch",
      rating: 4.8,
      stock: 9,
      featured: false,
    },
  ];
}